# Generated by Django 3.0.7 on 2020-06-09 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_remove_snippet_highlighted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['-created']},
        ),
    ]
