# Generated by Django 3.0.7 on 2020-06-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20200609_0656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['title']},
        ),
    ]
