# Generated by Django 3.0.7 on 2020-06-10 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_snippet_published_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='published_on',
        ),
    ]
